In [1]:
import pandas as pd

In [2]:
# abrimos archivo original
df = pd.read_csv('../Data/Data.csv', sep=';')

In [3]:
df

,time,shift,crew,hour,equipment,equipment_type,equipment_equipment_type,total,efectivo,d_prog,...,distance_down,distance_down_level,distance_up,distance_up_level,expected_time,lift_down,lift_down_level,lift_up,lift_up_level,travel_time
0,2022-01-01 00:00:00.000,A,E4,0,C-04,Truck,CAT 789-D,3600.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,2022-01-01 00:00:00.000,A,E4,0,C-14,Truck,CAT 789-D,3600.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,2022-01-01 00:00:00.000,A,E4,0,C-15,Truck,CAT 789-D,3600.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,2022-01-01 00:00:00.000,A,E4,0,C820,Truck,Kom.930EN,3600.0,3361.0,0.0,...,400,2568,400,4552,1259,-20,-46,20,41,1385
4,2022-01-01 00:00:00.000,A,E4,0,C823,Truck,Kom.930EN,3600.0,3487.0,0.0,...,335,2883,135,3553,1003,-23,-39,13,45,1403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2254316,2024-02-29 00:00:00.000,B,E1,11,C934,Truck,Kom.930E-4SE,3600.0,3130.0,0.0,...,0,332,4861,2254,1691,0,-9,406,45,1942
2254317,2024-02-29 00:00:00.000,B,E1,11,C935,Truck,Kom.930E-4SE,3600.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2254318,2024-02-29 00:00:00.000,B,E1,11,C951,Truck,Kom.980E5,3600.0,3367.0,0.0,...,5593,284,43,1302,1006,-487,-3,2,5,995
2254319,2024-02-29 00:00:00.000,B,E1,11,C957,Truck,Kom.980E5,3600.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2254320,2024-02-29 00:00:00.000,B,E1,11,G126,Truck,Kom.930ER,3600.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
# lo guardamos como parquet
df.to_parquet('../Data/Data.parquet', index=False)